### ISSUE TITLE
Add s_timme to bs-react-native slide

### ISSUE THREAD

**Issue by wokalski** [MarcelCutts/reason-speeddate-talk#1]
`bs-react-native` is collaborative work by @s_t and me. His twitter handle is `@s_timme`.

**Comment by MarcelCutts** [comment]
<img width="1296" alt="screen shot 2017-05-22 at 19 13 13" src="https://cloud.githubusercontent.com/assets/5721314/26322437/fd312782-3f22-11e7-9230-a69534f09281.png">

Done!
